services:
  - docker

branches:
  only:
  - master
  - develop

jobs:
  include:
    - stage: deploy
      if: tag IS present
      script:
      - echo "tag"
    - stage: test
      script:
      - cd tests
      - sh ./test.sh
