services:
  - docker

branches:
  only:
  - master
  - develop

jobs:
  include:
    - stage: deploy
      on:
        tags: true
      script:
      - echo "tag present"
    - stage: test
      script:
      - cd tests
      - sh ./test.sh
